# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-homelab-docs
  namespace: flux-system
spec:
  targetNamespace: web
  commonMetadata:
    labels:
      app.kubernetes.io/name: &app homelab-docs
  interval: 10m
  path: ./kubernetes/main/apps/web/homelab-docs/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  wait: false
  postBuild:
    substitute:
      APP: *app
      APP_SUBDOMAIN: docs
