---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &name changedetection
spec:
  releaseName: *name
  interval: 30m
  maxHistory: 3
  chart:
    spec:
      chart: changedetection-io
      version: 0.11.11
      sourceRef:
        kind: HelmRepository
        name: gabe565
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/dgtlmoon/changedetection.io
      tag: 0.45.8.1
    env:
      BASE_URL: https://change.cfg.sh/
    ingress:
      main:
        enabled: true
        hosts:
          - host: &host change.cfg.sh
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
        ingressClassName: nginx
        annotations:
          gethomepage.dev/name: change-detection
          gethomepage.dev/enabled: 'true'
          gethomepage.dev/group: monitoring
          gethomepage.dev/icon: changedetection-io.png
    data:
      enabled: true
      mountPath: /datastore
      size: 1Gi
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
