---
apiVersion: v1
kind: Secret
metadata:
  name: redis-authentik
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: AUTHENTIK_REDIS_PASSWORD
    secret-generator.v1.mittwald.de/type: string
    secret-generator.v1.mittwald.de/length: '32'
