---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kured
  namespace: system
spec:
  releaseName: kured
  interval: 30m
  maxHistory: 3
  chart:
    spec:
      chart: kured
      version: 5.3.2
      sourceRef:
        kind: HelmRepository
        name: kubereboot
        namespace: flux-system
  values:
    metrics:
      create: true
      namespace: monitoring
