# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-mealie
  namespace: &namespace selfhosted
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: &app mealie
  interval: 30m
  timeout: 5m
  path: ./cluster/kubernetes/apps/selfhosted/mealie/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
  wait: true
  components:
    - ../../../../componentsvolsync/hetzner
    - ../../../../componentssso-secret
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CLAIM: mealie-config
