---
game_version: "~1.21.0"
mods_dir: /mods
hooks:
  download:
    pre_run: "rm -rf {{.ModsDir}}/*.zip" # clear out old mods
mods:
  - id: primitivesurvival
    version: 4.0.3
  # - id: ExpandedFoods
  #   version: 1.7.4
  # - id: ACulinaryArtillery
  #   version: 1.2.5
  - id: CarryOn
    version: 1.12.1
  - id: BetterRuins
    version: 0.5.6
  - id: th3dungeon
    version: 0.4.5
  # - id: VintageRCon
  #   version: 1.0.0
  - id: webcartographer
    version: 0.9.0
  - id: pspeltpatch
    version: 0.0.2
  # - id: chiseltoolslite
  #   version: 1.15.1
