---
k3s_release_version: "v1.27.3+k3s1"
k3s_install_hard_links: true
k3s_become: true

k3s_server_manifests_urls:
  - url: https://raw.githubusercontent.com/metallb/metallb/v0.13.10/config/manifests/metallb-native.yaml
    filename: metallb-native.yaml
