# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-renovate-operator
  namespace: &namespace ci
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: renovate-operator
  interval: 30m
  timeout: 5m
  path: ./cluster/kubernetes/apps/ci/renovate-operator/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
  wait: true
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-renovate-jobs
  namespace: &namespace ci
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: renovate-operator
  interval: 30m
  timeout: 5m
  path: ./cluster/kubernetes/apps/ci/renovate-operator/jobs
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
  wait: true
