# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-romm
  namespace: flux-system
spec:
  targetNamespace: games
  commonMetadata:
    labels:
      app.kubernetes.io/name: &app romm
  interval: 30m
  timeout: 5m
  path: ./cluster/kubernetes/apps/games/romm/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
  wait: true
  components:
    - ../../../../componentssso-secret
    - ../../../../componentsdragonfly
    - ../../../../componentspostgres
    - ../../../../componentsvolsync/hetzner
    - ../../../../componentskeda/nas-nfs-scaler
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 5Gi
