---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &name authentik
spec:
  releaseName: *name
  interval: 30m
  maxHistory: 3
  chart:
    spec:
      chart: authentik
      version: 2023.10.5
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  values:
    env:
      AUTHENTIK_DISABLE_UPDATE_CHECK: 'true'
      AUTHENTIK_REDIS__HOST: authentik-redis.security.svc.cluster.local
      AUTHENTIK_REDIS__PORT: 6379
    envValueFrom:
      AUTHENTIK_SECRET_KEY:
        secretKeyRef:
          name: authentik
          key: secret_key
      AUTHENTIK_POSTGRESQL__HOST:
        secretKeyRef:
          name: &secret pg-db-authentik-app
          key: host
      AUTHENTIK_POSTGRESQL__PORT:
        secretKeyRef:
          name: *secret
          key: port
      AUTHENTIK_POSTGRESQL__NAME:
        secretKeyRef:
          name: *secret
          key: dbname
      AUTHENTIK_POSTGRESQL__USER:
        secretKeyRef:
          name: *secret
          key: username
      AUTHENTIK_POSTGRESQL__PASSWORD:
        secretKeyRef:
          name: *secret
          key: password
      AUTHENTIK_REDIS__PASSWORD:
        secretKeyRef:
          name: authentik-redis
          key: AUTHENTIK_REDIS_PASSWORD
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - host: sec.cloud.home
          paths:
            - path: /
              pathType: Prefix
      annotations:
        gethomepage.dev/name: *name
        gethomepage.dev/description: auth
        gethomepage.dev/enabled: 'true'
        gethomepage.dev/group: management
        gethomepage.dev/icon: authentik.png
    prometheus:
      serviceMonitor:
        create: true
    resources:
      server:
        requests:
          cpu: 75m
          memory: 768Mi
        limits:
          memory: 1G
      worker:
        requests:
          cpu: 30m
          memory: 384Mi
        limits:
          memory: 512Mi
