---
apiVersion: v1
kind: Secret
metadata:
  name: authentik
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: secret_key
    secret-generator.v1.mittwald.de/type: string
    secret-generator.v1.mittwald.de/length: '16'
