---
buildarr:
  watch_config: true
  update_days:
    - "monday"
    - "tuesday"
    - "wednesday"
    - "thursday"
    - "friday"
    - "saturday"
    - "sunday"
  update_times:
    - "03:00"

prowlarr:
  hostname: prowlarr.downloads.svc.cluster.local
  port: 80
  protocol: http
  api_key: ${PROWLARR_API_KEY}
  settings:
    indexers:
      indexers:
        delete_unmanaged: true
        definitions:
          DrunkenSlug:
            type: newznab
            enable: true
            sync_profile: Standard
            priority: 25
            fields:
              baseUrl: https://drunkenslug.com
              apiPath: /api
            secret_fields:
              apiKey: '${DS_API_KEY}'
    apps:
      applications:
        delete_unmanaged: true
        definitions:
          Radarr:
            type: radarr
            prowlarr_url: http://prowlarr.downloads.svc.cluster.local
            base_url: http://radarr.downloads.svc.cluster.local
            sync_level: full-sync
            sync_categories:
            - movies/hd
            - movies/bluray
            - movies/sd
            - movies/web-dl
            - movies/dvd
            - movies/foreign
            - movies/x265
            - movies/other
            - movies
            - movies/uhd
            - movies/3d
            sync_reject_blocklisted_torrent_hashes: false
            api_key: '${RADARR_API_KEY}'
          Sonarr:
            type: sonarr
            prowlarr_url: http://prowlarr.downloads.svc.cluster.local
            base_url: http://sonarr.downloads.svc.cluster.local
            sync_level: full-sync
            sync_categories:
            - tv
            - tv/uhd
            - tv/web-dl
            - tv/foreign
            - tv/x265
            - tv/other
            - tv/sd
            - tv/hd
            sync_reject_blocklisted_torrent_hashes: false
            api_key: '${SONARR_API_KEY}'
            anime_sync_categories:
            - tv/anime
            sync_anime_standard_format_search: false
    download_clients:
      delete_unmanaged: true
      definitions:
        SABnzbd:
          enable: true
          priority: 1
          type: sabnzbd
          host: sabnzbd.downloads.svc.cluster.local
          port: 80
          api_key: '${SABNZBD_API_KEY}'
          category: prowlarr
          client_priority: default

radarr:
  hostname: radarr.downloads.svc.cluster.local
  port: 80
  protocol: http
  api_key: ${RADARR_API_KEY}
  settings:
    download_clients:
      delete_unmanaged: true
      definitions:
        SABnzbd:
          enable: true
          remove_completed_downloads: true
          remove_failed_downloads: true
          priority: 1
          type: sabnzbd
          hostname: http://sabnzbd.downloads.svc.cluster.local
          port: 80
          use_ssl: false
          url_base: null
          api_key: '${SABNZBD_API_KEY}'
          category: movies

sonarr:
  hostname: sonarr.downloads.svc.cluster.local
  port: 80
  protocol: http
  api_key: ${SONARR_API_KEY}
  settings:
    download_clients:
      enable_completed_download_handling: true
      redownload_failed: true
      delete_unmanaged: true
      definitions:
        SABnzbd:
          enable: true
          remove_completed_downloads: true
          remove_failed_downloads: true
          type: sabnzbd
          host: http://sabnzbd.downloads.svc.cluster.local
          port: 80
          use_ssl: false
          api_key: '${SABNZBD_API_KEY}'
          category: tv
