---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &name weave
spec:
  chart:
    spec:
      chart: weave-gitops
      sourceRef:
        kind: HelmRepository
        name: ww-gitops
  interval: 30m
  values:
    adminUser:
      create: true
      username: &admin_user admin
    rbac:
      create: true
      impersonationResourceNames:
        - *admin_user
    fullnameOverride: *name
    ingress:
      className: nginx
      enabled: true
      hosts:
        - host: &host weave.cfg.sh
          paths:
            - path: /
              pathType: Prefix
              service:
                name: weave
                port: http
      tls:
        - hosts:
            - *host
      annotations:
        gethomepage.dev/name: *name
        gethomepage.dev/description: gitops ui
        gethomepage.dev/enabled: 'true'
        gethomepage.dev/group: management
        gethomepage.dev/icon: kubernetes.png
  valuesFrom:
    - kind: Secret
      name: weave-gitops
      valuesKey: password_hash
      targetPath: adminUser.passwordHash
