---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  releaseName: kube-prometheus-stack
  interval: 30m
  maxHistory: 3
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 55.11.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    prometheus:
      prometheusSpec:
        resources:
          requests:
            cpu: 384m
            memory: 2Gi
          limits:
            memory: 4Gi
        podMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        ruleSelectorNilUsesHelmValues: false
      ingress:
        enabled: true
        hosts:
          - &prom-host prom.cfg.sh
        tls:
          - hosts:
              - *prom-host
        annotations:
          gethomepage.dev/name: prometheus
          gethomepage.dev/enabled: 'true'
          gethomepage.dev/group: '${HOMEPAGE_CATEGORY}'
          gethomepage.dev/icon: prometheus.png
    grafana:
      grafanaSpec:
        resources:
          requests:
            cpu: 20m
            memory: 400Mi
          limits:
            memory: 700Mi
      ingress:
        enabled: true
        hosts:
          - &graf-host graf.cfg.sh
        tls:
          - hosts:
              - *graf-host
        annotations:
          gethomepage.dev/name: grafana
          gethomepage.dev/enabled: 'true'
          gethomepage.dev/group: '${HOMEPAGE_CATEGORY}'
          gethomepage.dev/icon: grafana.png
    alertmanager:
      alertmanagerSpec:
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
          limits:
            memory: 100Mi
      ingress:
        enabled: true
        hosts:
          - &am-host am.cfg.sh
        tls:
          - hosts:
              - *am-host
        annotations:
          gethomepage.dev/name: alertmanager
          gethomepage.dev/enabled: 'true'
          gethomepage.dev/group: '${HOMEPAGE_CATEGORY}'
          gethomepage.dev/icon: alertmanager.png
