---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: secret-generator
  namespace: system
spec:
  releaseName: secret-generator
  interval: 30m
  maxHistory: 3
  chart:
    spec:
      chart: kubernetes-secret-generator
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: kubernetes-secret-generator
        namespace: flux-system
  values:
    image:
      registry: ghcr.io
      repository: belodetek/kubernetes-secret-generator
      tag: 0.0.4
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 192Mi
