# passbcrypt generation: https://gchq.github.io/CyberChef/#recipe=Bcrypt(12)To_Hex('None',0)

[[users]]
    name = "search"
    uidnumber = 5000
    primarygroup = 6500
    passbcrypt = "{{ .GLAUTH_SEARCH_PSW_BCRYPT }}"
    [[users.capabilities]]
        action = "search"
        object = "*"

[[users]]
    name = "steve"
    mail = "steve@${DOMAIN}"
    givenname = "steve"
    uidnumber = 5001
    primarygroup = 6502
    othergroups = [ 6501 ]
    passbcrypt = "{{ .GLAUTH_STEVE_PSW_BCRYPT }}"

[[users]]
    name = "cl"
    mail = "{{ .GLAUTH_CL_EMAIL }}"
    uidnumber = 5002
    primarygroup = 6502
    passbcrypt = "{{ .GLAUTH_CL_PSW_BCRYPT }}"
