# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-flux-instance
  namespace: flux-system
spec:
  targetNamespace: flux-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: flux-instance
  interval: 30m
  timeout: 5m
  path: ./cluster/kubernetes/core/flux-system/flux-instance
  prune: false # bad idea to prune this
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
  wait: true
  dependsOn:
    - name: core-flux-operator
