# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ci
resources:
  - ./namespace.yaml
  - ./actions-runner-controller/ks.yaml
  - ./renovate-operator/ks.yaml
