# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minecraft-users
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: minecraft
    creationPolicy: Merge
  data:
    - secretKey: whitelist
      remoteRef:
        key: MINECRAFT_SURVIVAL_WHITELIST
    - secretKey: ops
      remoteRef:
        key: MINECRAFT_SURVIVAL_OPS
