---
apiVersion: v1
kind: Secret
metadata:
  name: minecraft-rcon
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: rcon_password
    secret-generator.v1.mittwald.de/type: string
    secret-generator.v1.mittwald.de/length: '16'
